-- Diagnosis codes for prescriptions (ICD-10-CM, which is in the public
-- domain). A curated set of the conditions an Indian outpatient clinic sees
-- most, not the full classification of about 70,000 codes: enough for the
-- search box to be useful, small enough to review by eye. Loading the full
-- CMS release file would be a data job, not a schema change.
--
-- keywords: everyday words doctors and patients use for the condition
-- ("BP", "sugar", "acidity") that the official title does not contain.
CREATE TABLE icd10_codes (
    code     VARCHAR(8)   PRIMARY KEY,
    title    VARCHAR(255) NOT NULL,
    keywords VARCHAR(255) NOT NULL DEFAULT ''
);

INSERT INTO icd10_codes (code, title, keywords) VALUES
-- Infections
('A09',     'Infectious gastroenteritis and colitis, unspecified', 'loose motions stomach flu'),
('A01.00',  'Typhoid fever, unspecified', 'enteric fever'),
('A90',     'Dengue fever [classical dengue]', 'dengue'),
('B54',     'Unspecified malaria', 'malaria'),
('B34.9',   'Viral infection, unspecified', 'viral fever'),
('B01.9',   'Varicella without complication', 'chickenpox'),
('B35.4',   'Tinea corporis', 'ringworm fungal'),
('B36.0',   'Pityriasis versicolor', 'fungal patches'),
('B86',     'Scabies', 'itch mites'),
('U07.1',   'COVID-19', 'covid coronavirus'),
-- Blood, endocrine, nutrition
('D50.9',   'Iron deficiency anemia, unspecified', 'anaemia low haemoglobin'),
('D64.9',   'Anemia, unspecified', 'anaemia'),
('E03.9',   'Hypothyroidism, unspecified', 'thyroid'),
('E05.90',  'Thyrotoxicosis, unspecified without thyrotoxic crisis or storm', 'hyperthyroid thyroid'),
('E10.9',   'Type 1 diabetes mellitus without complications', 'sugar'),
('E11.9',   'Type 2 diabetes mellitus without complications', 'sugar dm'),
('E11.65',  'Type 2 diabetes mellitus with hyperglycemia', 'uncontrolled sugar'),
('R73.03',  'Prediabetes', 'borderline sugar'),
('E55.9',   'Vitamin D deficiency, unspecified', 'vit d'),
('E53.8',   'Deficiency of other specified B group vitamins', 'b12 vitamin'),
('E66.9',   'Obesity, unspecified', 'overweight'),
('E78.5',   'Hyperlipidemia, unspecified', 'cholesterol lipids'),
('E86.0',   'Dehydration', ''),
('E28.2',   'Polycystic ovarian syndrome', 'pcos pcod'),
-- Mental health and nervous system
('F41.1',   'Generalized anxiety disorder', 'anxiety'),
('F32.9',   'Major depressive disorder, single episode, unspecified', 'depression'),
('F90.9',   'Attention-deficit hyperactivity disorder, unspecified type', 'adhd'),
('G47.00',  'Insomnia, unspecified', 'sleep'),
('G43.909', 'Migraine, unspecified, not intractable, without status migrainosus', 'headache'),
('G44.209', 'Tension-type headache, unspecified, not intractable', 'headache'),
('R51.9',   'Headache, unspecified', ''),
('G40.909', 'Epilepsy, unspecified, not intractable, without status epilepticus', 'seizures fits'),
('G56.00',  'Carpal tunnel syndrome, unspecified upper limb', 'wrist numbness'),
('G51.0',   'Bell''s palsy', 'facial palsy'),
('R42',     'Dizziness and giddiness', 'giddiness'),
-- Eye and ear
('H10.9',   'Unspecified conjunctivitis', 'pink eye red eye'),
('H26.9',   'Unspecified cataract', ''),
('H60.90',  'Unspecified otitis externa, unspecified ear', 'ear infection'),
('H61.20',  'Impacted cerumen, unspecified ear', 'ear wax'),
('H66.90',  'Otitis media, unspecified, unspecified ear', 'ear infection'),
('H81.10',  'Benign paroxysmal vertigo, unspecified ear', 'bppv vertigo'),
-- Heart and circulation
('I10',     'Essential (primary) hypertension', 'high blood pressure bp htn'),
('I20.9',   'Angina pectoris, unspecified', 'chest pain'),
('I25.10',  'Atherosclerotic heart disease of native coronary artery without angina pectoris', 'cad coronary'),
('I48.91',  'Unspecified atrial fibrillation', 'af irregular heartbeat'),
('I50.9',   'Heart failure, unspecified', ''),
('I83.90',  'Asymptomatic varicose veins of unspecified lower extremity', ''),
('R00.2',   'Palpitations', ''),
('R07.9',   'Chest pain, unspecified', ''),
-- Respiratory, nose and throat
('J00',     'Acute nasopharyngitis [common cold]', 'cold coryza'),
('J01.90',  'Acute sinusitis, unspecified', 'sinus'),
('J02.9',   'Acute pharyngitis, unspecified', 'sore throat'),
('J03.90',  'Acute tonsillitis, unspecified', 'tonsils'),
('J35.01',  'Chronic tonsillitis', 'tonsils'),
('J06.9',   'Acute upper respiratory infection, unspecified', 'urti cold cough'),
('J11.1',   'Influenza due to unidentified influenza virus with other respiratory manifestations', 'flu'),
('J18.9',   'Pneumonia, unspecified organism', ''),
('J20.9',   'Acute bronchitis, unspecified', 'chest infection'),
('J30.9',   'Allergic rhinitis, unspecified', 'sneezing allergy'),
('J32.9',   'Chronic sinusitis, unspecified', 'sinus'),
('J34.2',   'Deviated nasal septum', 'dns'),
('J44.9',   'Chronic obstructive pulmonary disease, unspecified', 'copd'),
('J45.909', 'Unspecified asthma, uncomplicated', 'wheeze'),
('R05.9',   'Cough, unspecified', ''),
('R06.02',  'Shortness of breath', 'breathlessness'),
-- Teeth and digestion
('K01.1',   'Impacted teeth', 'wisdom tooth'),
('K02.9',   'Dental caries, unspecified', 'cavity tooth decay'),
('K04.7',   'Periapical abscess without sinus', 'tooth abscess'),
('K05.10',  'Chronic gingivitis, plaque induced', 'gums bleeding'),
('K08.9',   'Disorder of teeth and supporting structures, unspecified', 'toothache'),
('K21.9',   'Gastro-esophageal reflux disease without esophagitis', 'gerd acidity reflux heartburn'),
('K27.9',   'Peptic ulcer, site unspecified, unspecified as acute or chronic, without hemorrhage or perforation', 'ulcer'),
('K29.70',  'Gastritis, unspecified, without bleeding', 'acidity'),
('K30',     'Functional dyspepsia', 'indigestion acidity'),
('K35.80',  'Unspecified acute appendicitis', ''),
('K40.90',  'Unilateral inguinal hernia, without obstruction or gangrene, not specified as recurrent', 'hernia'),
('K58.9',   'Irritable bowel syndrome without diarrhea', 'ibs'),
('K59.00',  'Constipation, unspecified', ''),
('K60.2',   'Anal fissure, unspecified', 'fissure'),
('K64.9',   'Unspecified hemorrhoids', 'piles'),
('K76.0',   'Fatty (change of) liver, not elsewhere classified', 'fatty liver nafld'),
('K80.20',  'Calculus of gallbladder without cholecystitis without obstruction', 'gallstones'),
('R10.13',  'Epigastric pain', 'stomach pain'),
('R10.9',   'Unspecified abdominal pain', 'stomach pain'),
('R11.2',   'Nausea with vomiting, unspecified', 'vomiting'),
('R19.7',   'Diarrhea, unspecified', 'loose motions'),
-- Skin and hair
('L02.91',  'Cutaneous abscess, unspecified', 'boil'),
('L20.9',   'Atopic dermatitis, unspecified', 'eczema'),
('L21.9',   'Seborrheic dermatitis, unspecified', 'dandruff'),
('L30.9',   'Dermatitis, unspecified', 'skin rash'),
('L40.0',   'Psoriasis vulgaris', 'psoriasis'),
('L50.9',   'Urticaria, unspecified', 'hives'),
('L63.9',   'Alopecia areata, unspecified', 'hair loss patches'),
('L65.9',   'Nonscarring hair loss, unspecified', 'hair fall'),
('L70.0',   'Acne vulgaris', 'pimples'),
('L80',     'Vitiligo', 'white patches'),
('R21',     'Rash and other nonspecific skin eruption', ''),
-- Bones, joints and muscles
('M06.9',   'Rheumatoid arthritis, unspecified', 'ra'),
('M10.9',   'Gout, unspecified', 'uric acid'),
('M17.9',   'Osteoarthritis of knee, unspecified', 'knee arthritis'),
('M19.90',  'Unspecified osteoarthritis, unspecified site', 'arthritis'),
('M25.561', 'Pain in right knee', 'knee pain'),
('M25.562', 'Pain in left knee', 'knee pain'),
('M25.511', 'Pain in right shoulder', 'shoulder pain'),
('M54.2',   'Cervicalgia', 'neck pain'),
('M54.16',  'Radiculopathy, lumbar region', 'slipped disc'),
('M54.30',  'Sciatica, unspecified side', 'sciatica'),
('M54.50',  'Low back pain, unspecified', 'backache'),
('M72.2',   'Plantar fascial fibromatosis', 'plantar fasciitis heel pain'),
('M75.00',  'Adhesive capsulitis of unspecified shoulder', 'frozen shoulder'),
('M77.10',  'Lateral epicondylitis, unspecified elbow', 'tennis elbow'),
('M79.7',   'Fibromyalgia', ''),
('M81.0',   'Age-related osteoporosis without current pathological fracture', 'osteoporosis'),
('S93.401A','Sprain of unspecified ligament of right ankle, initial encounter', 'ankle sprain'),
-- Kidney, urinary and reproductive
('N18.9',   'Chronic kidney disease, unspecified', 'ckd'),
('N20.0',   'Calculus of kidney', 'kidney stone'),
('N39.0',   'Urinary tract infection, site not specified', 'uti'),
('N40.0',   'Benign prostatic hyperplasia without lower urinary tract symptoms', 'bph prostate'),
('R31.9',   'Hematuria, unspecified', 'blood in urine'),
('R35.0',   'Frequency of micturition', 'frequent urination'),
('N76.0',   'Acute vaginitis', ''),
('N91.2',   'Amenorrhea, unspecified', 'missed periods'),
('N92.0',   'Excessive and frequent menstruation with regular cycle', 'heavy periods'),
('N94.6',   'Dysmenorrhea, unspecified', 'period pain'),
('N95.1',   'Menopausal and female climacteric states', 'menopause'),
('Z34.90',  'Encounter for supervision of normal pregnancy, unspecified, unspecified trimester', 'antenatal pregnancy'),
-- Children
('P59.9',   'Neonatal jaundice, unspecified', 'newborn jaundice'),
('Z00.129', 'Encounter for routine child health examination without abnormal findings', 'well baby'),
-- General
('R50.9',   'Fever, unspecified', 'pyrexia'),
('R53.83',  'Other fatigue', 'tiredness weakness'),
('R63.4',   'Abnormal weight loss', ''),
('T78.40XA','Allergy, unspecified, initial encounter', 'allergy'),
('Z00.00',  'Encounter for general adult medical examination without abnormal findings', 'health check-up'),
('Z01.20',  'Encounter for dental examination and cleaning without abnormal findings', 'dental check-up'),
('Z23',     'Encounter for immunization', 'vaccination vaccine');

-- A prescription may carry the code; free-text-only diagnoses stay valid.
ALTER TABLE prescriptions
    ADD COLUMN diagnosis_code VARCHAR(8) REFERENCES icd10_codes (code);
